urls.py
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('',
    url(r'^$', 'common.views.base'),
    url(r'^reset/$', 'common.views.reset_password_instance'),
    url(r'^password/(?P<token>.*)/$', 'common.views.reset_password'),
    url(r'^user/login/', 'account.views.login'),
    url(r'^logout/?$',  'django.contrib.auth.views.logout_then_login'),
    url(r'^user/register/$',  'account.views.register'),
    url(r'^user/change_password/$',  'profile.views.password_change'),
    url(r'^user/change_email/$',  'profile.views.email_change'),
    url(r'^user/change_first_name/$',  'profile.views.first_name_change'),
    url(r'^user/change_last_name/$',  'profile.views.last_name_change'),
    url(r'^user/change_personal_info/$',  'profile.views.personal_info_change'),
    url(r'^user/check/$',  'profile.views.check_user'),
    url(r'^profile/$',  'profile.views.myprofile'),
    url(r'^account/change-password$',  'account.views.change_password'),
    url(r'^stream/clan$',  'alliance.views.get_stream'),
    url(r'^profile/stream/clan$',  'profile.views.stream_clan'),
    url(r'^profile/widget-lvl$',  'profile.views.widget_lvl'),
    url(r'^profile/widget-territory$',  'profile.views.widget_territory'),
    url(r'^profile/dismiss-clan$',  'profile.views.dismiss_clan'),
    url(r'^profile/get_users/$',  'profile.views.get_users'),
    url(r'^profile/sendmessage/$',  'profile.views.send_message'),
    url(r'^profile/friendrequest/$',  'profile.views.friendrequest'),
    url(r'^profile/(?P<profile_id>\d+)$',  'profile.views.profiles'),
    url(r'^profile/(?P<profile_id>\d+)/add_friend/$',  'profile.views.add_friend_request'),
    url(r'^profile/(?P<profile_id>\d+)/un_friend/$',  'profile.views.un_friend'),
    url(r'^notification/seen/(?P<notification_id>\d+)$',  'notification.views.seen_notification'),
    url(r'^get-ranks/(?P<limit>\d+)$',  'ranks.views.get_ranks'),
    url(r'^ranks/$',  'ranks.views.ranks'),
    url(r'^alliance/create/$',  'alliance.views.create'),
    url(r'^clan$',  'alliance.views.my_clan'),
    url(r'^clan/avatar$',  'alliance.views.upload_avatar'),
    url(r'^clan/del-member$',  'alliance.views.del_member'),
    url(r'^clan/create-news$',  'alliance.views.create_news'),
    url(r'^clan/name-change$',  'alliance.views.name_change'),
    url(r'^clan/vote-news$',  'alliance.views.vote_news'),
    url(r'^clan/check-like-state$',  'alliance.views.check_like_state'),
    url(r'^alliance/request/$',  'alliance.views.request'),
    url(r'^alliance/process_request/$',  'alliance.views.process_request'),
    url(r'^battle/request/war$',  'battle.views.war_request'),
    url(r'^external-api/login/$',  'external-api.views.login'),
    url(r'^external-api/checkin/$',  'external-api.views.checkingin'),
    url(r'^map/$',  direct_to_template, {'template': 'map.html'}),
    url(r'^territory/create$',  'territory.views.create_territory'),
    url(r'^territory/verify$',  'territory.views.verify_territory'),
    url(r'^location/get-locations$',  'location.views.get_locations'),
    url(r'^site_media/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^feedback', include('feedback.urls')),
    url(r'^territory/load', 'territory.views.load_territory'),
    url(r'^territory/upgrade', 'territory.views.upgrade'),
    url(r'^territory/name', 'territory.views.change_name'),
    url(r'^territory/color', 'territory.views.change_color'),
    url(r'^facebook/login$', 'facebook.views.login'),
    url(r'^facebook/authentication_callback$', 'facebook.views.authentication_callback'),
    url(r'^sentry/', include('sentry.web.urls')),
    url(r'^google/login$', 'django_openid_auth.views.login_begin', name='openid-login'),
    url(r'^login-complete/google$', 'django_openid_auth.views.login_complete', name='openid-complete'),
    url(r'^mu-95f975c2-b4b3a524-2bd24a2d-36d223f6.txt$', 'tests.views.blitz'),

)

handler404 = 'common.views.base'

urlpatterns += staticfiles_urlpatterns()

location/models.py
from django.db import models
from account.models import UserProfile

class Location(models.Model):
    name = models.CharField(max_length=30)
    lat = models.FloatField(max_length=30)
    lng = models.FloatField(max_length=30)

    territory = models.ForeignKey("territory.Territory", related_name="locations", null=True)
    
    subscription = models.FloatField(max_length=20, default=1)

class Loyalty(models.Model):
    value = models.IntegerField(default=0, max_length=30)
    location = models.ForeignKey(Location)
    userProfile = models.ForeignKey(UserProfile)
    active = models.BooleanField(default=True)

territory/models.py
from django.db import models
from Items.models import Defends
from account.models import UserProfile
from location.models import Location

class Points(models.Model):
    lat = models.CharField(max_length=30)
    lng = models.CharField(max_length=30)
    
class Territory(models.Model):
    defense = models.IntegerField(max_length=6, null=True)

    name = models.CharField(max_length=50, default="My territory")
    price = models.IntegerField(max_length=6)
    area = models.IntegerField(max_length=6)
    
    points = models.ManyToManyField(Points, null=True)

    owner = models.ForeignKey(UserProfile)

    lvl = models.IntegerField(default=1)

    color = models.CharField(max_length=50, default="#ffe019")

territory/forms.py
from django.forms import ModelForm
from territory.models import Territory

class ChangeName(ModelForm):
    class Meta:
         model = Territory
         fields = ('name',)
class ChangeColor(ModelForm):
    class Meta:
         model = Territory
         fields = ('color',)

territory/views.py
from django.utils import simplejson
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.template import loader
from django.template.context import RequestContext, Context
from battle.models import Battle
from checkin.models import Checkin
from territory.forms import ChangeName, ChangeColor
from territory.models import *
from location.models import *
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def create_territory(request):
    if request.method == 'POST':

        up = UserProfile.objects.get(user=request.user)
            
        try:
            terrytories = Territory.objects.get(owner=up)
            return HttpResponse(simplejson.dumps({'error': 'You stupid asshole, just a territory! Go and conquer something!!!'}))
        except Exception:
            area = int(float(request.POST.get('area')))/10
            money = up.money
            if area <= money:
                territory = Territory.objects.create(price=0, area=0, owner=up)
                path =  request.POST.get('path')
                print path
                points = path.split(';')
                for point in points:
                    lat = point.split(',')[0]
                    lng = point.split(',')[1]
                    geoPoint = Points.objects.create(lat=lat, lng=lng)
                    territory.points.add(geoPoint)
                up.money = money - area
                loc =  request.POST.get('locations')
                points = loc.split(';')

                for point in points:
                    try:
                        lat = point.split(',')[0]
                        lng = point.split(',')[1]

                        location = Location.objects.get(lat=float(lat), lng=float(lng))
                        location.territory = territory
                        location.save()

                    except Exception:
                        pass
                up.save()
                return HttpResponse(simplejson.dumps({'nice': 'Congratz! You have a territory :)', 'id': territory.id, 'lng': territory.points.all()[0].lng, 'lat':territory.points.all()[0].lat}))
            else:
               return HttpResponse(simplejson.dumps({'error': "Sry...you don't have enough money"}))
    return HttpResponse('Not here!')

@csrf_exempt
def verify_territory(request):
    if request.method == 'POST':
        try:
            path =  request.POST.get('path')
            points = path.split(';')
            minx = 999.00
            maxx = -999.00
            miny = 999.00
            maxy = -999.00

            for point in points:
                lat = float(point.split(',')[0])
                lng = float(point.split(',')[1])
                if lat < minx:
                    minx = lat
                if lat > maxx:
                    maxx = lat
                if lng < miny:
                    miny = lng
                if lng >maxy:
                    maxy = lng

            locations = Location.objects.filter(lat__range=(minx, maxx), lng__range=(miny, maxy))

            if locations:
                json_locations = []
                for location in locations:
                    json_locations.append(simplejson.dumps({'lat': location.lat, 'lng': location.lng}))

                return HttpResponse(simplejson.dumps({'locations': json_locations}))
            else:
                return HttpResponse(simplejson.dumps({'error': "There aren't any locations in this territory!"}))
        except Exception:
             return HttpResponse(simplejson.dumps({'error': "There was an error when we tried to verify your territory!"}))
    return HttpResponse('Not here!')

def load_territory(request):
    if request.method == 'GET':
        id = request.GET.get('id')
        territory = Territory.objects.get(pk=id)
        checkins = Checkin.objects.filter(location__territory = territory).order_by('-created_at')[:5]
        locations = Location.objects.filter(territory=territory)
        notification_template = loader.get_template('territory_widget.html')
        context = {}
        context['territory'] = territory
        context['checkins'] = checkins
        context['locations'] = locations

        try:
            battle = Battle.objects.get(defender = territory.owner, active=True)
            context['battle'] = battle
        except Exception:
            pass
        
        c = Context(context)
        message = notification_template.render(c)
        return HttpResponse(message)
    return HttpResponse('Not good enough')

@csrf_exempt
def upgrade(request):
    if request.method == 'POST':
        id = request.POST.get('id')

        territory = Territory.objects.get(pk=id)
        up = UserProfile.objects.get(user=request.user)

        if up.money >= territory.lvl * 1000:
            territory.lvl = territory.lvl + 1
            territory.save()
            up.money = up.money - (territory.lvl-1) * 1000
            up.save()
            return HttpResponse(simplejson.dumps({'message': "You've just upgrade your territory"}))
        return HttpResponse(simplejson.dumps({'message': 'You need ' +str(territory.lvl * 1000) + ' outcoins to upgrade your territory!'}))
    return HttpResponse(simplejson.dumps({'message': "Just a system error! Don't panic...."}))

@csrf_exempt
def change_name(request):
    if request.method == 'POST':
        terid = request.POST.get('id')
        territory = Territory.objects.get(pk=terid)
        form = ChangeName(request.POST, instance=territory)
        form.save()
        return HttpResponse(simplejson.dumps({'message': 'The name has been change!'}))
    return HttpResponse('Not here!')

@csrf_exempt
def change_color(request):
    if request.method == 'POST':
        terid = request.POST.get('id')
        territory = Territory.objects.get(pk=terid)
        form = ChangeColor(request.POST, instance=territory)
        form.save()
        return HttpResponse(simplejson.dumps({'message': 'The color has been change!'}))
    return HttpResponse('Not here!')

territory/templates/territory_widget.html
<div class="territory_widget_territory" data-id="{{ territory.id }}">
    <script type="text/javascript">
        $(document).ready(function(){
            $('#colorSelector').css('backgroundColor', '{{ territory.color }}');
           $('#colorSelector').ColorPicker({
                    color: '{{ territory.color }}',
                    onShow: function (colpkr) {
                        $(colpkr).fadeIn(500);
                        return false;
                    },
                    onHide: function (colpkr) {
                        $(colpkr).fadeOut(500);
                        return false;
                    },
                    onChange: function (hsb, hex, rgb) {
                        $('#colorSelector').css('backgroundColor', '#' + hex);
                        console.log(app.territoryArray[{{ territory.id }}]);
                        app.territoryArray[{{ territory.id }}].fillColor = '#' + hex;
                        app.territoryArray[{{ territory.id }}].strokeColor = '#' + hex;
                        app.territoryArray[{{ territory.id }}].setMap(app.map);
                        $.post('/territory/color', {'color': '#' + hex, 'id': {{ territory.id }}}, function(data){
                            
                        })
                    }
           });

        });
    </script>
    {% if battle %}
        <div id="territory_widget_atack" class="clearfix">
            <div class="territory_widget_atacker_info clearfix">
                <a id="show_venues" href="#">Venues</a>
                    <p>Under atack by </p>

                    <p class="small_avatar territory_widget_atack_avatar clearfix" style="background-image: url({{ battle.attacker.gravatar_url }}?s=30)">
                    <a href="/profile/{{ battle.attacker.id }}"><img src="{{ battle.attacker.gravatar_url }}?s=30" alt="avatar" title="{{ battle.attacker.user.username }}"/></a>
                    </p>
            </div>
        </div>
    {% else %}
        <a id="show_venues" href="#">Venues</a>
    {% endif %}
            <div class="territory_widget_venues">
                <ul>
                    {% for venue in locations %}
                        <li class="clearfix">
                            <div class="territory_widget_venues_venue" id="territoryVenue" data-lat="{{ venue.lat }}" data-lng="{{ venue.lng }}">{{ venue.name }}</div>
                                {% if battle %}
                                    <div class="territory_widget_venues_venue_loyalty">
                                        {{ venue.loyalty_set.all.0 }}
                                    </div>
                                {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>

    <div id="territory_widget_stats" class="clearfix">
        <label>Color:</label><div id="colorSelector" style="width:20px; height: 20px; float:right;"></div>
        <ul><li>Level: {{ territory.lvl }}</li><li>Venues: {{ locations.count }}</li></ul>
        <div id="territory_widget_level_box" data-id="{{ territory.id }}" >
            <div id="territory_widget_level_box_top" >+1</div>
            <div id="territory_widget_level_box_bottom" >upgrade</div>
        </div>
    </div>

    <ul id="territory_widget_checkins" class="clearfix">

        <li>Territory Stats</li>
        {% for checkin in checkins %}
             <li class="clearfix">
               <p class="small_avatar territory_widget_stats_avatar clearfix" style="background-image: url({{ checkin.user.gravatar_url }}?s=30)">
                    <a href="/profile/{{ checkin.user.user.id }}"><img src="{{ STATIC_URL }}img/user/default.png" alt="avatar"/></a>
               </p>

               <ul><li>@ {{ checkin.location.name }}</li><li>{{ checkin.created_at }}</li></ul>

               <div class="territory_widget_checkins_profit"></div>
            </li>
        {% endfor %}

    </ul>

    <div id="show_checkins" class="territory_widget_checkins_button"><a href="#">Show Territory Stats</a></div>

 </div>